// Schema-driven early field validation (issue #475). The canonicalize + enum/range
// algorithm is the SSOT `hosted-field-validation-core`, authored in apps/web and
// projected VERBATIM into ./generated by the hosted-execution-manifest codegen — the CLI
// submodule cannot import apps/web TS, and a hand-copy here would let the casing / range
// rules drift from the Web boundary. This module only injects the CLI's plain-Error
// factory and keeps the established (endpointKey, fields, input) signature its callers
// use. The Web boundary stays the AUTHORITATIVE gate; this is pre-submit feedback so the
// agent gets an immediate field-level error (e.g. seedance resolution "999p") instead of
// waiting for the round-trip.
import {
  HOSTED_MEDIA_REFERENCE_URI_PREFIX,
  assertModelledFieldValuesInRange as assertModelledFieldValuesInRangeCore,
} from './generated/hosted-field-validation-core.generated.js';
import type { ManifestField } from './hosted-manifest-index.js';

export function assertModelledFieldValuesInRange(
  endpointKey: string,
  fields: readonly ManifestField[],
  input: Record<string, unknown>,
): void {
  assertModelledFieldValuesInRangeCore(
    endpointKey,
    fields,
    input,
    (message) => new Error(message),
  );
}

export function assertNoUnknownModelledFields(
  endpointKey: string,
  fields: readonly ManifestField[],
  input: Record<string, unknown>,
): void {
  const modelled = new Set(fields.map((field) => field.name));
  const unknown = Object.keys(input).filter((key) => !modelled.has(key));
  if (unknown.length > 0) {
    throw new Error(
      `${endpointKey} input carries field(s) outside the manifest contract: ${unknown.join(', ')}.`,
    );
  }
}

// The only reference forms the hosted media boundary can actually use: a
// provider-fetchable HTTPS URL, a persistent hosted-media reference, or inline
// data-URI bytes. Manifest-declared local paths have already been validated and
// staged by `resolveManifestMediaInputs` before this final transport gate.
const MEDIA_URL_SCHEME_PREFIXES = [
  'https://',
  HOSTED_MEDIA_REFERENCE_URI_PREFIX,
  'data:',
] as const;

function hasAllowedMediaUrlScheme(value: string): boolean {
  return MEDIA_URL_SCHEME_PREFIXES.some((prefix) => value.startsWith(prefix));
}

function formatRejectedMediaUrlValue(value: string): string {
  return value.length > 120 ? `${value.slice(0, 120)}…` : value;
}

// Client-side gate for `media-url` typed fields, run on the prepared input at
// the same call sites as assertModelledFieldValuesInRange. The Web boundary
// stays authoritative; this is pre-submit feedback for an unsupported value.
export function assertMediaUrlFieldSchemes(
  endpointKey: string,
  fields: readonly ManifestField[],
  input: Record<string, unknown>,
): void {
  for (const field of fields) {
    if (field.class === 'runner-managed' || field.type !== 'media-url') {
      continue;
    }
    if (!Object.hasOwn(input, field.name)) {
      continue;
    }
    const raw = input[field.name];
    const entries = Array.isArray(raw) ? raw : [raw];
    for (const entry of entries) {
      if (typeof entry !== 'string' || !entry.trim()) {
        continue;
      }
      const value = entry.trim();
      if (!hasAllowedMediaUrlScheme(value)) {
        throw new Error(
          `${endpointKey} ${field.name} must be an https:// URL, a ${HOSTED_MEDIA_REFERENCE_URI_PREFIX} reference, or a data: URI; received "${formatRejectedMediaUrlValue(value)}". ` +
            `Pass an existing local file through ${field.flag ?? `the ${field.name} field`}, or use a supported remote media value.`,
        );
      }
    }
  }
}
