// Schema-driven early field validation (issue #475). The canonicalize + enum/range
// algorithm is the SSOT `hosted-field-validation-core`, authored in apps/web and
// projected VERBATIM into ./generated by the hosted-execution-manifest codegen — the CLI
// submodule cannot import apps/web TS, and a hand-copy here would let the casing / range
// rules drift from the Web boundary. This module only injects the CLI's plain-Error
// factory and keeps the established (endpointKey, fields, input) signature its callers
// use. The Web boundary stays the AUTHORITATIVE gate; this is pre-submit feedback so the
// agent gets an immediate field-level error (e.g. seedance resolution "999p") instead of
// waiting for the round-trip.

import { assertModelledFieldValuesInRange as assertModelledFieldValuesInRangeCore } from './generated/hosted-field-validation-core.generated.js';
import type { ManifestField } from './hosted-manifest-index.js';

export function assertModelledFieldValuesInRange(
  endpointKey: string,
  fields: readonly ManifestField[],
  input: Record<string, unknown>,
): void {
  assertModelledFieldValuesInRangeCore(
    endpointKey,
    fields,
    input,
    (message) => new Error(message),
  );
}
